### ISSUE TITLE
Totally sorry, but this is not related to Frogwood

### ISSUE THREAD

**Issue by turdlar** [KaneChopwood/frogwood#1]
Hi - i'm sorry to butt in on your project like this, but i couldn't find an alternative to contacting you. 
Your MOHAA Stalingrad map for pavlov is not showing up for me anymore, and the link to its page is throwing an error at me. Please consider fixing this, as it is one of my favourite maps for Pavlov.

Also, i would love some pointers on how to recreate a map like that, as faithfully as you managed to do it.

If this is an inappropriate way of contacting you, then i totally get it, and will stay away if don't appreciate this kind of contact - just let me know.

**Comment by KaneChopwood** [comment]
Hey mate. I discontinued all work for Pavlov VR due to a disagreement between me and the game's creator. I removed the map(s) from workshop as soon an update made them unplayable and the realization struck i wouldn't have the time nor energy to maintain them. My interest in creating content for the game is still pretty low, but I do appreciate and am grateful for the interest people have shown for the maps. I just can't make any promises.

Now as far as pointers go for remaking maps (without porting) : 
- Scale and proportions are extremely important. I've managed to open the original map in an compatible q3radiant editor, made top down screenshots of the geometry with scale references, layed those out in unreal and started building from that (with a lot of testing!). I've made stuff a bit more spacious for VR, but from that point on it was just gut feeling.
- Keep it simple. Stalingrad was an easy map because its small and the geometry isn't complex. Most of it is basic square brush work, the smaller details (such as the basement staircase) are custom models/textures i've created and imported on the go. 
- Have a basic material library ready with texture variants for floors, walls, ceilings and maybe some misc. stuff. I've remade them from scratch in Substance Painter based on some screenshots i took in MOHAA. This took quite some time and isn't an easy task, so if you are new to all this i'd suggest using shared materials from other map creators. 

Hope this helps a bit. Good luck.
